export const CONNECT_SERVICE_URL = 'CONNECT_SERVICE_URL';
export const CTP_TAX_CALCULATOR_EXTENSION_KEY = 'ctpTaxCalculatorExtension';
export const TAX_PROVIDER_API_TOKEN = 'TAX_PROVIDER_API_TOKEN';
export const TAX_CODE_MAPPING_JSON_KEY = 'TAX_CODE_MAPPING_JSON';