export const CONNECT_SERVICE_URL = 'CONNECT_SERVICE_URL';
export const CTP_TAX_CALCULATOR_EXTENSION_KEY = 'ctpTaxCalculatorExtension';
export const STRIPE_API_TOKEN = 'STRIPE_API_TOKEN';
export const TAX_CODE_CATEGORY_MAPPING_JSON_KEY = 'TAX_CODE_CATEGORY_MAPPING_JSON';